openapi: 3.0.0
info:
  title: Phillips-Connect Technologies API
  version: '1.0'
  description: ''
  contact:
    name: Brent Whitney
    email: bwhitney@phillipsind.com
servers:
  - url: 'https://api.phillips-connect.com/api'
    description: Prod API
paths:
  /gateway/reports:
    get:
      summary: Retrieve gateway reports
      tags:
        - Gateway
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  '':
                    $ref: ./device-report/models/report.v1.yaml
                  total_reports:
                    type: integer
                  current_page:
                    type: integer
                  total_pages:
                    type: integer
            multipart/form-data:
              schema:
                type: object
                properties: {}
            text/html:
              schema:
                $ref: ./device-report/models/report.v1.yaml
            text/plain:
              schema:
                type: object
                properties:
                  '':
                    $ref: ./device-report/models/report.v1.yaml
                  total_reports:
                    type: integer
                    description: Total reports based on the search criteria specified in the request
                  current_page:
                    type: integer
                    description: Current page index
                  total_pages:
                    type: integer
                    description: Total number of pages based on the result set
          headers: {}
      operationId: get-device-report
      parameters:
        - schema:
            type: string
          in: query
          name: gateway-id
          description: |
            Required to search by gateway-id (imei). If the query-method is set to GATEWAY_NUMBER, the gateway-id must be specificied
        - schema:
            type: string
            enum:
              - DATETIME
              - REPORT_NUMBER
              - GATEWAY_NUMBER
          in: query
          name: query-method
          description: |
            Indicates how to query the server

            REPORT-NUMBER is a sequential number assigned for each report that is generated across all customer devices

            GATEWAY_NUMBER is a sequential number assigned for each report that is generated per customer device

            DATETIME is the datetime of when the report is received by the PCT server
        - schema:
            type: string
          in: query
          name: from
          description: 'From: [server datetime | report number | gateway number]'
        - schema:
            type: string
          in: query
          name: to
          description: 'To: [server datetime | report number | gateway number]'
        - schema:
            type: integer
          in: query
          name: results-per-page
          description: Number of results per page. Default is 1000.
        - schema:
            type: integer
          in: query
          name: page-index
          description: 'For a multi-page query, returns the specified page (from 1 to total_pages)'
      description: "Returns historical gateway reports. Reports are generated based on PCT event types.\n\nOpen ended queries will pull recent reports across all gateways for a given customer (based on the data you are authorized to see, or you can limit this by providing a gateway-id (imei). \n\nFor further filtering, you can pass in a query method and provide the appropriate 'from' and 'to'. See specific instructions in the appropriate fields.   "
    parameters: []
components:
  schemas: {}
  securitySchemes:
    API Key - 1:
      type: http
      scheme: bearer
tags:
  - name: Gateway
